### ISSUE TITLE
Mobile version review

### ISSUE THREAD

**Issue by Mehdi-Rh** [i-max-xi/Appiah-Gyimah-Maxwell#15]
This issue is a review of the mobile version codes.

**Comment by Mehdi-Rh** [comment]
There is a hyperlink that doesn't refer to any page, check the link https://github.com/i-max-xi/Microverse-Week-1_P2/pull/11#discussion_r788444469

**Comment by i-max-xi** [comment]
I used a tags since I anticipated they would lead to my social media pages.
But i would disable them for now since they are not in use.

**Comment by Yoz21** [comment]
There are the same commit titles (fix stylint errors) that make the commit history unclean.

**Comment by i-max-xi** [comment]
Thanks on noticing that for me. I would check it next time
